### ISSUE TITLE
Revision by @GaraziArregui

### ISSUE THREAD

**Issue by mberasategi** [MSGW2018/A6#17]
- [x] [Education: Benefits](https://github.com/MSGW2018/A6/blob/master/education/benefits.md)
- [x] [Education: Future](https://github.com/MSGW2018/A6/blob/master/education/future.md)
- [x] [Education: Limitations](https://github.com/MSGW2018/A6/blob/master/education/limitations.md)

**Comment by GaraziArregui** [comment]
I have just finished all my revisions!

**Comment by mberasategi** [comment]
Hi @GaraziArregui , if you have finished all the revisions assigned to you please go ahead and [open a pull request](https://github.com/MSGW2018/A6/blob/master/CONTRIBUTING.md#stage-2-revision) as described in the CONTRIBUTING document.
