### ISSUE TITLE
Revision by @carlagob

### ISSUE THREAD

**Issue by mberasategi** [MSGW2018/A6#21]
- [x] [Politics: E-government](https://github.com/MSGW2018/A6/blob/master/politics/E-government.md)
- [x] [Politics: Hacktivism](https://github.com/MSGW2018/A6/blob/master/politics/Hactivism.md)
- [x] [Politics: Open government](https://github.com/MSGW2018/A6/blob/master/politics/open.government.md)

**Comment by carlagob** [comment]
Hi! I would include more visual elements to make the page  easier to read.  So far I've  added more text and sections, as well as links and media, such as emojis, links to YouTube videos and images. 

Apart from that, the work is really good! There were very little spelling and grammar mistakes. And the information was right and clear. 

 @MSGW2018/group5  #21

**Comment by carlagob** [comment]
I have made some changes on the "E-government" page:

-  Textual additions: introduction, what is it's main objective, it's benefits, and the role that TICs play.
- I added sections with titles written in bold.
- I added a link of a YouTube video and an image, one link and one emoji.
- I've changed some part of the text.

@MSGW2018/group5 @mberasategi #21

**Comment by carlagob** [comment]
I have made some changes on the "Hacktivism" page:

- Textual additions: I added different sections  (Is hacktivism good or bad?, Hacktivism or cyberterrorism?, What are the most common targets for hacktivists?, and examples).
- I added titles written in bold.
- I added a link of a YouTube video and emojis.
- I've changed some part of the text.
- I added  eight other links.

@MSGW2018/group5 @mberasategi #21

**Comment by carlagob** [comment]
I have made some changes on the "Open Government" page:

- Textual additions: I added different sections (What is an Open Government?, Open Government services, Technology and Open Government, and Different initiatives).
- I added titles written in bold.
- I added a link of a YouTube video, an image and one emoji.
- I've changed some part of the text.
- I added five other links.

@MSGW2018/group5 @mberasategi #21

**Comment by carlagob** [comment]
Overall there were very little spelling mistakes and the information was correct.  :thumbsup:

**Comment by mberasategi** [comment]
Hi @carlagob , good to see you back :relaxed: . If you have finished all the revisions assigned to you please go ahead and [open a pull request](https://github.com/MSGW2018/A6/blob/master/CONTRIBUTING.md#stage-2-revision) as described in the CONTRIBUTING document.
