### ISSUE TITLE
Revision by @aitorxagar

### ISSUE THREAD

**Issue by mberasategi** [MSGW2018/A6#33]
- [x] [Knowledge generation: Collective intelligence](https://github.com/MSGW2018/A6/blob/master/knowledge-generation/collective-intelligence.md)
- [x] [Knowledge generation: Crowdsourcing](https://github.com/MSGW2018/A6/blob/master/knowledge-generation/crowdsourcing.md)
- [x] [Knowledge generation: Ordering the digital disorder](https://github.com/MSGW2018/A6/blob/master/knowledge-generation/ordering-digital-disorder.md)

**Comment by aitorxagar** [comment]
- [ ] [Knowledge generation: README](https://github.com/MSGW2018/A6/blob/master/knowledge-generation/README.md)

**Comment by mberasategi** [comment]
Hi @aitorxagar , please add your comments to 1d14d6a96630065e56a0dcab221fe09594b1365e as comments here. Then, if you have finished all the revisions assigned to you please go ahead and [open a pull request](https://github.com/MSGW2018/A6/blob/master/CONTRIBUTING.md#stage-2-revision) as described in the CONTRIBUTING document.

**Comment by aitorxagar** [comment]
Hi! I would include some visual element to make the page nicer! Apart from that, the work is really good! @MSGW2018/group7 #33 1d14d6a
