### ISSUE TITLE
Revision by @laidasalsamendi

### ISSUE THREAD

**Issue by mberasategi** [MSGW2018/A6#34]
- [x] [Economy: Crowdfunding](https://github.com/MSGW2018/A6/blob/master/economy/crowdfunding.md)
- [x] [Economy: The Long Tail](https://github.com/MSGW2018/A6/blob/master/economy/long-tail.md)
- [x] [Economy: Trade and exchange of direct services](https://github.com/MSGW2018/A6/blob/master/economy/trade-exchange-direct.md)

**Comment by laidasalsamendi** [comment]
Changes made in the last page: Trade and Exchange of direct services on the Internet

- Added a link to "digital services", with a small explanation of what they are
- Some grammatical changes
- Added a video to each service explaining how they work and how to make money through them
- Textual editing 

@MSGW2018/group4 @mberasategi

**Comment by mberasategi** [comment]
Hi @laidasalsamendi , if you have finished all the revisions assigned to you please go ahead and [open a pull request](https://github.com/MSGW2018/A6/blob/master/CONTRIBUTING.md#stage-2-revision) as described in the CONTRIBUTING document.
