### ISSUE TITLE
Revision by @MaialenSorozabalbere

### ISSUE THREAD

**Issue by mberasategi** [MSGW2018/A6#36]
- [x] [Economy: Crowdfunding](https://github.com/MSGW2018/A6/blob/master/economy/crowdfunding.md)
- [x] [Economy: The Long Tail](https://github.com/MSGW2018/A6/blob/master/economy/long-tail.md)
- [x] [Economy: Trade and exchange of direct services](https://github.com/MSGW2018/A6/blob/master/economy/trade-exchange-direct.md)

**Comment by MaialenSorzabalbere** [comment]
1. Economy: crowdfunding
The text is very appropiate and its design and structure too. The photo located at the begining is not available to see... but te rest it is oerfect!

2. Economy: The Long Tail
The design and structure is very appropiate and the image too. However, there is not any space between the "**" and the text so it does not look like it should. But, in general the page and content is so good!

3. Economy: Trade and exchange of direct services
As the first one, the text, content and its design is very appropiate, but the first image is not avalable to see. 

All in all, i have the same problem... I think that in my page happens the same with the image... In generela this trhee sections are very good!! Good job!
